theme = "gruvbox_dark_hard"

[editor]
true-color = true
bufferline = "always"

[editor.cursor-shape]
insert = "bar"

[editor.lsp]
display-messages = true
display-inlay-hints = true

[keys.normal]
G = "goto_file_end"
esc = ["collapse_selection", "keep_primary_selection"]
